// src/components/Navbar.tsx
import { Link, useNavigate } from 'react-router-dom';
import { ShoppingCart, User, LogOut, Search, Store } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { storage } from '@/lib/storage';
import { useState, useEffect } from 'react';

interface NavbarProps {
  cartItemsCount: number;
  onCartClick: () => void;
}

export const Navbar = ({ cartItemsCount, onCartClick }: NavbarProps) => {
  const navigate = useNavigate();
  const [user, setUser] = useState(storage.getUser());

  useEffect(() => {
    const checkUser = () => setUser(storage.getUser());
    window.addEventListener('storage', checkUser);
    window.addEventListener('user-changed', checkUser);
    return () => {
      window.removeEventListener('storage', checkUser);
      window.removeEventListener('user-changed', checkUser);
    };
  }, []);

  const handleLogout = () => {
    storage.clearUser();
    storage.clearCart();
    window.dispatchEvent(new Event('user-changed'));
    navigate('/auth');
  };

  return (
    <nav className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container mx-auto px-4">
        <div className="flex h-16 items-center justify-between">
          <Link to="/" className="flex items-center gap-2 font-semibold text-xl">
            <Store className="h-6 w-6 text-primary" />
            <span>ShopHub</span>
          </Link>

          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => navigate('/products')}
              className="hidden sm:inline-flex"
            >
              <Search className="h-5 w-5" />
            </Button>

            {user ? (
              <>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => navigate('/orders')}
                  className="hidden sm:inline-flex"
                >
                  <User className="h-5 w-5" />
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={onCartClick}
                  className="relative"
                >
                  <ShoppingCart className="h-5 w-5" />
                  {cartItemsCount > 0 && (
                    <Badge 
                      variant="destructive" 
                      className="absolute -top-1 -right-1 h-5 w-5 flex items-center justify-center p-0 text-xs"
                    >
                      {cartItemsCount}
                    </Badge>
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={handleLogout}
                >
                  <LogOut className="h-5 w-5" />
                </Button>
              </>
            ) : (
              <Button onClick={() => navigate('/auth')}>
                Login
              </Button>
            )}
          </div>
        </div>
      </div>
    </nav>
  );
};

// qwik-app/src/components/Navbar.tsx
import { component$, $, useComputed$ } from '@builder.io/qwik';
import { Link, useNavigate } from '@builder.io/qwik-city';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { useAppContext } from '@/contexts/app-context';
import { LogoutIcon, SearchIcon, ShoppingCartIcon, StoreIcon, UserIcon } from '@/components/icons';

export const Navbar = component$(() => {
  const app = useAppContext();
  const navigate = useNavigate();

  const cartCount = useComputed$(() =>
    app.state.cart.reduce((sum, item) => sum + item.quantity, 0)
  );

  const handleLogout = $(() => {
    app.setUser(null);
    app.clearCart();
    navigate('/auth');
  });

  return (
    <nav class="sticky top-0 z-50 w-full border-b bg-white/90 backdrop-blur supports-[backdrop-filter]:bg-white/60">
      <div class="container mx-auto px-4">
        <div class="flex h-16 items-center justify-between">
          <Link href="/" class="flex items-center gap-2 font-semibold text-xl">
            <StoreIcon class="h-6 w-6 text-primary" />
            <span>ShopHub</span>
          </Link>

          <div class="flex items-center gap-4">
            <Button
              variant="ghost"
              size="icon"
              class="hidden sm:inline-flex"
              onClick$={() => navigate('/products')}
            >
              <SearchIcon class="h-5 w-5" />
            </Button>

            {app.state.user ? (
              <>
                <Button
                  variant="ghost"
                  size="icon"
                  class="hidden sm:inline-flex"
                  onClick$={() => navigate('/orders')}
                >
                  <UserIcon class="h-5 w-5" />
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  class="relative"
                  onClick$={() => app.toggleCart(true)}
                >
                  <ShoppingCartIcon class="h-5 w-5" />
                  {cartCount.value > 0 && (
                    <Badge
                      variant="destructive"
                      class="absolute -top-1 -right-1 h-5 w-5 flex items-center justify-center p-0 text-xs"
                    >
                      {cartCount.value}
                    </Badge>
                  )}
                </Button>
                <Button variant="ghost" size="icon" onClick$={handleLogout}>
                  <LogoutIcon class="h-5 w-5" />
                </Button>
              </>
            ) : (
              <Button onClick$={() => navigate('/auth')}>Login</Button>
            )}
          </div>
        </div>
      </div>
    </nav>
  );
});
