// qwik-app/src/routes/checkout/index.tsx
import { $, component$, useComputed$, useStore, useTask$ } from '@builder.io/qwik';
import { useNavigate } from '@builder.io/qwik-city';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Label } from '@/components/ui/Label';
import { Separator } from '@/components/ui/Separator';
import { useAppContext } from '@/contexts/app-context';
import { storage } from '@/lib/storage';
import { formatCurrency } from '@/lib/utils';
import type { CartItem, Order } from '@/types';
import { ArrowRightIcon, CreditCardIcon, PackageIcon } from '@/components/icons';

interface CheckoutState {
  cart: CartItem[];
  isProcessing: boolean;
}

export default component$(() => {
  const app = useAppContext();
  const navigate = useNavigate();
  const state = useStore<CheckoutState>({ cart: [], isProcessing: false });

  useTask$(({ track }) => {
    track(() => app.state.user);
    if (!app.state.user) {
      navigate('/auth');
    }
  });

  useTask$(({ track }) => {
    track(() => app.state.cart);
    const cart = app.state.cart.length ? app.state.cart : storage.getCart();
    if (!cart.length) {
      app.addToast({
        title: 'Cart is empty',
        description: 'Add some items to your cart first',
      });
      navigate('/products');
    }
    state.cart = cart;
  });

  const subtotal = useComputed$(() =>
    state.cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  );
  const shipping = useComputed$(() => (subtotal.value > 100 ? 0 : 9.99));
  const tax = useComputed$(() => subtotal.value * 0.1);
  const total = useComputed$(() => subtotal.value + shipping.value + tax.value);

  const handleCheckout = $(async (event: Event) => {
    event.preventDefault();
    if (!state.cart.length || state.isProcessing) return;
    state.isProcessing = true;

    setTimeout(() => {
      const order: Order = {
        id: `ORD-${Date.now()}`,
        items: state.cart,
        total: total.value,
        date: new Date().toISOString(),
        status: 'completed',
      };
      storage.saveOrder(order);
      app.clearCart();
      app.addToast({
        title: 'Order placed successfully!',
        description: `Order #${order.id} has been confirmed`,
      });
      state.isProcessing = false;
      navigate('/orders');
    }, 2000);
  });

  if (!state.cart.length) {
    return null;
  }

  return (
    <div class="min-h-screen py-8">
      <div class="container mx-auto px-4 max-w-6xl">
        <Button variant="ghost" onClick$={() => navigate(-1)} class="mb-6">
          <ArrowRightIcon class="h-4 w-4 mr-2 rotate-180" />
          Back
        </Button>

        <h1 class="text-4xl font-bold mb-8">Checkout</h1>

        <div class="grid lg:grid-cols-3 gap-8">
          <div class="lg:col-span-2">
            <form preventdefault:submit onSubmit$={handleCheckout} class="space-y-6">
              <Card>
                <CardHeader>
                  <CardTitle class="flex items-center gap-2">
                    <PackageIcon class="h-5 w-5" />
                    Shipping Information
                  </CardTitle>
                </CardHeader>
                <CardContent class="space-y-4">
                  <div class="grid sm:grid-cols-2 gap-4">
                    <div class="space-y-2">
                      <Label for="firstName">First Name</Label>
                      <Input id="firstName" required />
                    </div>
                    <div class="space-y-2">
                      <Label for="lastName">Last Name</Label>
                      <Input id="lastName" required />
                    </div>
                  </div>
                  <div class="space-y-2">
                    <Label for="address">Address</Label>
                    <Input id="address" required />
                  </div>
                  <div class="grid sm:grid-cols-3 gap-4">
                    <div class="space-y-2">
                      <Label for="city">City</Label>
                      <Input id="city" required />
                    </div>
                    <div class="space-y-2">
                      <Label for="state">State</Label>
                      <Input id="state" required />
                    </div>
                    <div class="space-y-2">
                      <Label for="zip">ZIP Code</Label>
                      <Input id="zip" required />
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle class="flex items-center gap-2">
                    <CreditCardIcon class="h-5 w-5" />
                    Payment Information
                  </CardTitle>
                </CardHeader>
                <CardContent class="space-y-4">
                  <div class="space-y-2">
                    <Label for="cardNumber">Card Number</Label>
                    <Input id="cardNumber" placeholder="1234 5678 9012 3456" required />
                  </div>
                  <div class="grid sm:grid-cols-3 gap-4">
                    <div class="space-y-2 sm:col-span-2">
                      <Label for="expiry">Expiry Date</Label>
                      <Input id="expiry" placeholder="MM/YY" required />
                    </div>
                    <div class="space-y-2">
                      <Label for="cvv">CVV</Label>
                      <Input id="cvv" placeholder="123" required />
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Button type="submit" size="lg" class="w-full" disabled={state.isProcessing}>
                {state.isProcessing ? 'Processing...' : `Place Order - ${formatCurrency(total.value)}`}
              </Button>
            </form>
          </div>

          <div class="lg:col-span-1">
            <Card class="sticky top-24">
              <CardHeader>
                <CardTitle>Order Summary</CardTitle>
              </CardHeader>
              <CardContent class="space-y-4">
                <div class="space-y-3">
                  {state.cart.map((item) => (
                    <div key={item.id} class="flex gap-3">
                      <img src={item.image} alt={item.title} class="h-16 w-16 object-contain rounded" />
                      <div class="flex-1 min-w-0">
                        <p class="font-medium text-sm line-clamp-2">{item.title}</p>
                        <p class="text-sm text-muted-foreground">Qty: {item.quantity}</p>
                      </div>
                      <p class="font-semibold text-sm">{formatCurrency(item.price * item.quantity)}</p>
                    </div>
                  ))}
                </div>

                <Separator />

                <div class="space-y-2">
                  <div class="flex justify-between text-sm">
                    <span>Subtotal</span>
                    <span>{formatCurrency(subtotal.value)}</span>
                  </div>
                  <div class="flex justify-between text-sm">
                    <span>Shipping</span>
                    <span>{shipping.value === 0 ? 'FREE' : formatCurrency(shipping.value)}</span>
                  </div>
                  <div class="flex justify-between text-sm">
                    <span>Tax</span>
                    <span>{formatCurrency(tax.value)}</span>
                  </div>
                  <Separator />
                  <div class="flex justify-between font-bold text-lg">
                    <span>Total</span>
                    <span class="text-primary">{formatCurrency(total.value)}</span>
                  </div>
                </div>

                {shipping.value === 0 && (
                  <div class="bg-accent/50 text-accent-foreground p-3 rounded-lg text-sm text-center">
                    🎉 You get free shipping!
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
});

// src/pages/Checkout.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { CartItem, Order } from '@/types';
import { storage } from '@/lib/storage';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { toast } from '@/hooks/use-toast';
import { ArrowLeft, CreditCard, Package } from 'lucide-react';

export default function Checkout() {
  const navigate = useNavigate();
  const [cart, setCart] = useState<CartItem[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    const user = storage.getUser();
    if (!user) {
      navigate('/auth');
      return;
    }

    const cartItems = storage.getCart();
    if (cartItems.length === 0) {
      toast({
        title: 'Cart is empty',
        description: 'Add some items to your cart first',
      });
      navigate('/products');
      return;
    }
    setCart(cartItems);
  }, [navigate]);

  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const shipping = subtotal > 100 ? 0 : 9.99;
  const tax = subtotal * 0.1;
  const total = subtotal + shipping + tax;

  const handleCheckout = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsProcessing(true);

    // Simulate payment processing
    setTimeout(() => {
      const order: Order = {
        id: `ORD-${Date.now()}`,
        items: cart,
        total,
        date: new Date().toISOString(),
        status: 'completed',
      };

      storage.saveOrder(order);
      storage.clearCart();
      
      toast({
        title: 'Order placed successfully!',
        description: `Order #${order.id} has been confirmed`,
      });

      setIsProcessing(false);
      navigate('/orders');
    }, 2000);
  };

  if (cart.length === 0) {
    return null;
  }

  return (
    <div className="min-h-screen py-8">
      <div className="container mx-auto px-4 max-w-6xl">
        <Button
          variant="ghost"
          onClick={() => navigate(-1)}
          className="mb-6"
        >
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back
        </Button>

        <h1 className="text-4xl font-bold mb-8">Checkout</h1>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Checkout Form */}
          <div className="lg:col-span-2">
            <form onSubmit={handleCheckout} className="space-y-6">
              {/* Shipping Information */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Package className="h-5 w-5" />
                    Shipping Information
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid sm:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="firstName">First Name</Label>
                      <Input id="firstName" required />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="lastName">Last Name</Label>
                      <Input id="lastName" required />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="address">Address</Label>
                    <Input id="address" required />
                  </div>
                  <div className="grid sm:grid-cols-3 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="city">City</Label>
                      <Input id="city" required />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="state">State</Label>
                      <Input id="state" required />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="zip">ZIP Code</Label>
                      <Input id="zip" required />
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Payment Information */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <CreditCard className="h-5 w-5" />
                    Payment Information
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="cardNumber">Card Number</Label>
                    <Input
                      id="cardNumber"
                      placeholder="1234 5678 9012 3456"
                      required
                    />
                  </div>
                  <div className="grid sm:grid-cols-3 gap-4">
                    <div className="space-y-2 sm:col-span-2">
                      <Label htmlFor="expiry">Expiry Date</Label>
                      <Input id="expiry" placeholder="MM/YY" required />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="cvv">CVV</Label>
                      <Input id="cvv" placeholder="123" required />
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Button
                type="submit"
                size="lg"
                className="w-full"
                disabled={isProcessing}
              >
                {isProcessing ? 'Processing...' : `Place Order - $${total.toFixed(2)}`}
              </Button>
            </form>
          </div>

          {/* Order Summary */}
          <div className="lg:col-span-1">
            <Card className="sticky top-24">
              <CardHeader>
                <CardTitle>Order Summary</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  {cart.map((item) => (
                    <div key={item.id} className="flex gap-3">
                      <img
                        src={item.image}
                        alt={item.title}
                        className="h-16 w-16 object-contain rounded"
                      />
                      <div className="flex-1 min-w-0">
                        <p className="font-medium text-sm line-clamp-2">
                          {item.title}
                        </p>
                        <p className="text-sm text-muted-foreground">
                          Qty: {item.quantity}
                        </p>
                      </div>
                      <p className="font-semibold text-sm">
                        ${(item.price * item.quantity).toFixed(2)}
                      </p>
                    </div>
                  ))}
                </div>

                <Separator />

                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span>Subtotal</span>
                    <span>${subtotal.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span>Shipping</span>
                    <span>{shipping === 0 ? 'FREE' : `$${shipping.toFixed(2)}`}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span>Tax</span>
                    <span>${tax.toFixed(2)}</span>
                  </div>
                  <Separator />
                  <div className="flex justify-between font-bold text-lg">
                    <span>Total</span>
                    <span className="text-primary">${total.toFixed(2)}</span>
                  </div>
                </div>

                {shipping === 0 && (
                  <div className="bg-accent/50 text-accent-foreground p-3 rounded-lg text-sm text-center">
                    🎉 You get free shipping!
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
