// qwik-app/src/routes/products/index.tsx
import { $, component$, useStore, useTask$, useVisibleTask$ } from '@builder.io/qwik';
import { useLocation, useNavigate } from '@builder.io/qwik-city';
import { Input } from '@/components/ui/Input';
import { ProductCard } from '@/components/ProductCard';
import { useAppContext } from '@/contexts/app-context';
import { api } from '@/lib/api';
import type { Product } from '@/types';
import { SearchIcon } from '@/components/icons';

interface ProductsState {
  products: Product[];
  filtered: Product[];
  categories: string[];
  loading: boolean;
  searchTerm: string;
  selectedCategory: string;
  sortBy: string;
}

export default component$(() => {
  const app = useAppContext();
  const navigate = useNavigate();
  const location = useLocation();
  const state = useStore<ProductsState>({
    products: [],
    filtered: [],
    categories: [],
    loading: true,
    searchTerm: '',
    selectedCategory: 'all',
    sortBy: 'default',
  });

  const handleAddToCart = $((product: Product) => {
    if (!app.state.user) {
      app.addToast({
        title: 'Please login',
        description: 'You need to login to add items to cart',
        variant: 'destructive',
      });
      navigate('/auth');
      return;
    }
    app.addToCart(product);
    app.addToast({
      title: 'Added to cart',
      description: `${product.title} has been added to your cart`,
    });
  });

  useVisibleTask$(async () => {
    try {
      const [products, categories] = await Promise.all([
        api.getAllProducts(),
        api.getCategories(),
      ]);
      state.products = products;
      state.categories = categories;
      const categoryParam = new URLSearchParams(location.url.search).get('category');
      if (categoryParam) {
        state.selectedCategory = categoryParam;
      }
    } catch (error) {
      console.error(error);
      app.addToast({
        title: 'Error',
        description: 'Failed to load products',
        variant: 'destructive',
      });
    } finally {
      state.loading = false;
    }
  });

  useTask$(({ track }) => {
    track(() => state.products);
    track(() => state.searchTerm);
    track(() => state.selectedCategory);
    track(() => state.sortBy);

    let result = [...state.products];

    if (state.selectedCategory !== 'all') {
      result = result.filter((p) => p.category === state.selectedCategory);
    }

    if (state.searchTerm) {
      const term = state.searchTerm.toLowerCase();
      result = result.filter((p) => p.title.toLowerCase().includes(term));
    }

    if (state.sortBy === 'price-low') {
      result.sort((a, b) => a.price - b.price);
    } else if (state.sortBy === 'price-high') {
      result.sort((a, b) => b.price - a.price);
    } else if (state.sortBy === 'rating') {
      result.sort((a, b) => b.rating.rate - a.rating.rate);
    }

    state.filtered = result;
  });

  return (
    <div class="min-h-screen py-8">
      <div class="container mx-auto px-4">
        <h1 class="text-4xl font-bold mb-8">All Products</h1>

        <div class="flex flex-col sm:flex-row gap-4 mb-8">
          <div class="relative flex-1">
            <SearchIcon class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search products..."
              value={state.searchTerm}
              onInput$={(_, element) => {
                state.searchTerm = element.value;
              }}
              class="pl-10"
            />
          </div>

          <select
            class="h-10 rounded-md border border-input bg-white px-3 text-sm"
            value={state.selectedCategory}
            onChange$={(_, element) => {
              state.selectedCategory = element.value;
            }}
          >
            <option value="all">All Categories</option>
            {state.categories.map((cat) => (
              <option key={cat} value={cat}>
                {cat.charAt(0).toUpperCase() + cat.slice(1)}
              </option>
            ))}
          </select>

          <select
            class="h-10 rounded-md border border-input bg-white px-3 text-sm"
            value={state.sortBy}
            onChange$={(_, element) => {
              state.sortBy = element.value;
            }}
          >
            <option value="default">Default</option>
            <option value="price-low">Price: Low to High</option>
            <option value="price-high">Price: High to Low</option>
            <option value="rating">Rating</option>
          </select>
        </div>

        {state.loading ? (
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {[1, 2, 3, 4, 5, 6, 7, 8].map((i) => (
              <div key={i} class="h-96 bg-secondary/30 rounded-lg animate-pulse" />
            ))}
          </div>
        ) : state.filtered.length === 0 ? (
          <div class="text-center py-16">
            <p class="text-muted-foreground text-lg">No products found</p>
          </div>
        ) : (
          <>
            <p class="text-muted-foreground mb-4">
              Showing {state.filtered.length} products
            </p>
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
              {state.filtered.map((product) => (
                <ProductCard key={product.id} product={product} onAddToCart$={handleAddToCart} />
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
});

// src/pages/Products.tsx
import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Product } from '@/types';
import { api } from '@/lib/api';
import { ProductCard } from '@/components/ProductCard';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Search, SlidersHorizontal } from 'lucide-react';
import { toast } from '@/hooks/use-toast';

interface ProductsProps {
  onAddToCart: (product: Product) => void;
}

export default function Products({ onAddToCart }: ProductsProps) {
  const [searchParams, setSearchParams] = useSearchParams();
  const [products, setProducts] = useState<Product[]>([]);
  const [filteredProducts, setFilteredProducts] = useState<Product[]>([]);
  const [categories, setCategories] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [sortBy, setSortBy] = useState<string>('default');

  useEffect(() => {
    const loadData = async () => {
      try {
        const [productsData, categoriesData] = await Promise.all([
          api.getAllProducts(),
          api.getCategories(),
        ]);
        setProducts(productsData);
        setCategories(categoriesData);

        // Check for category from URL
        const categoryParam = searchParams.get('category');
        if (categoryParam) {
          setSelectedCategory(categoryParam);
        }
      } catch (error) {
        toast({
          title: 'Error',
          description: 'Failed to load products',
          variant: 'destructive',
        });
      } finally {
        setLoading(false);
      }
    };
    loadData();
  }, [searchParams]);

  useEffect(() => {
    let result = [...products];

    // Filter by category
    if (selectedCategory !== 'all') {
      result = result.filter((p) => p.category === selectedCategory);
    }

    // Filter by search term
    if (searchTerm) {
      result = result.filter((p) =>
        p.title.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    // Sort
    if (sortBy === 'price-low') {
      result.sort((a, b) => a.price - b.price);
    } else if (sortBy === 'price-high') {
      result.sort((a, b) => b.price - a.price);
    } else if (sortBy === 'rating') {
      result.sort((a, b) => b.rating.rate - a.rating.rate);
    }

    setFilteredProducts(result);
  }, [products, selectedCategory, searchTerm, sortBy]);

  return (
    <div className="min-h-screen py-8">
      <div className="container mx-auto px-4">
        <h1 className="text-4xl font-bold mb-8">All Products</h1>

        {/* Filters */}
        <div className="flex flex-col sm:flex-row gap-4 mb-8">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search products..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10"
            />
          </div>

          <Select value={selectedCategory} onValueChange={setSelectedCategory}>
            <SelectTrigger className="w-full sm:w-[200px]">
              <SlidersHorizontal className="h-4 w-4 mr-2" />
              <SelectValue placeholder="Category" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Categories</SelectItem>
              {categories.map((cat) => (
                <SelectItem key={cat} value={cat}>
                  {cat.charAt(0).toUpperCase() + cat.slice(1)}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          <Select value={sortBy} onValueChange={setSortBy}>
            <SelectTrigger className="w-full sm:w-[200px]">
              <SelectValue placeholder="Sort by" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="default">Default</SelectItem>
              <SelectItem value="price-low">Price: Low to High</SelectItem>
              <SelectItem value="price-high">Price: High to Low</SelectItem>
              <SelectItem value="rating">Rating</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Products Grid */}
        {loading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {[1, 2, 3, 4, 5, 6, 7, 8].map((i) => (
              <div key={i} className="h-96 bg-secondary/30 rounded-lg animate-pulse" />
            ))}
          </div>
        ) : filteredProducts.length === 0 ? (
          <div className="text-center py-16">
            <p className="text-muted-foreground text-lg">No products found</p>
          </div>
        ) : (
          <>
            <p className="text-muted-foreground mb-4">
              Showing {filteredProducts.length} products
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
              {filteredProducts.map((product) => (
                <ProductCard
                  key={product.id}
                  product={product}
                  onAddToCart={onAddToCart}
                />
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}
