// qwik-app/src/components/CartDrawer.tsx
import { component$, useComputed$, $ } from '@builder.io/qwik';
import { useNavigate } from '@builder.io/qwik-city';
import { useAppContext } from '@/contexts/app-context';
import { Button } from '@/components/ui/Button';
import { MinusIcon, PlusIcon, TrashIcon } from '@/components/icons';
import { formatCurrency } from '@/lib/utils';

export const CartDrawer = component$(() => {
  const app = useAppContext();
  const navigate = useNavigate();

  const total = useComputed$(() =>
    app.state.cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  );

  const handleCheckout = $(() => {
    app.toggleCart(false);
    navigate('/checkout');
  });

  return (
    <div
      class={`fixed inset-0 z-50 transition ${
        app.state.cartOpen ? 'pointer-events-auto' : 'pointer-events-none'
      }`}
    >
      <div
        class={`absolute inset-0 bg-black/30 transition-opacity duration-300 ${
          app.state.cartOpen ? 'opacity-100' : 'opacity-0'
        }`}
        onClick$={() => app.toggleCart(false)}
      />
      <aside
        class={`absolute right-0 top-0 h-full w-full sm:max-w-lg bg-white shadow-xl transition-transform duration-300 flex flex-col ${
          app.state.cartOpen ? 'translate-x-0' : 'translate-x-full'
        }`}
      >
        <div class="px-6 py-4 border-b">
          <h2 class="text-lg font-semibold">Shopping Cart ({app.state.cart.length})</h2>
        </div>
        <div class="flex-1 overflow-y-auto px-6 py-4 space-y-4">
          {app.state.cart.length === 0 ? (
            <div class="flex flex-col items-center justify-center text-center h-full text-muted-foreground gap-3">
              <p>Your cart is empty</p>
              <Button
                variant="outline"
                onClick$={() => {
                  app.toggleCart(false);
                  navigate('/products');
                }}
              >
                Continue Shopping
              </Button>
            </div>
          ) : (
            app.state.cart.map((item) => (
              <div key={item.id} class="flex gap-4 p-4 rounded-lg border bg-card">
                <img src={item.image} alt={item.title} class="h-20 w-20 object-contain rounded" />
                <div class="flex-1">
                  <h4 class="font-medium line-clamp-2 mb-2">{item.title}</h4>
                  <p class="font-semibold text-primary">{formatCurrency(item.price)}</p>
                  <div class="flex items-center gap-2 mt-2">
                    <Button
                      variant="outline"
                      size="icon"
                      class="h-8 w-8"
                      onClick$={() => app.updateQuantity(item.id, item.quantity - 1)}
                    >
                      <MinusIcon class="h-4 w-4" />
                    </Button>
                    <span class="w-8 text-center font-medium">{item.quantity}</span>
                    <Button
                      variant="outline"
                      size="icon"
                      class="h-8 w-8"
                      onClick$={() => app.updateQuantity(item.id, item.quantity + 1)}
                    >
                      <PlusIcon class="h-4 w-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      class="h-8 w-8 ml-auto text-red-500"
                      onClick$={() => app.removeItem(item.id)}
                    >
                      <TrashIcon class="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
        {app.state.cart.length > 0 && (
          <div class="border-t px-6 py-4 space-y-4">
            <div class="flex justify-between text-lg font-semibold">
              <span>Total</span>
              <span class="text-primary">{formatCurrency(total.value)}</span>
            </div>
            <Button class="w-full" size="lg" onClick$={handleCheckout}>
              Proceed to Checkout
            </Button>
          </div>
        )}
      </aside>
    </div>
  );
});

// src/components/CartDrawer.tsx
import { CartItem } from '@/types';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetFooter,
} from '@/components/ui/sheet';
import { Button } from '@/components/ui/button';
import { Minus, Plus, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

interface CartDrawerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  items: CartItem[];
  onUpdateQuantity: (id: number, quantity: number) => void;
  onRemoveItem: (id: number) => void;
}

export const CartDrawer = ({
  open,
  onOpenChange,
  items,
  onUpdateQuantity,
  onRemoveItem,
}: CartDrawerProps) => {
  const navigate = useNavigate();
  const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0);

  const handleCheckout = () => {
    onOpenChange(false);
    navigate('/checkout');
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="w-full sm:max-w-lg flex flex-col">
        <SheetHeader>
          <SheetTitle>Shopping Cart ({items.length})</SheetTitle>
        </SheetHeader>

        <div className="flex-1 overflow-y-auto py-4">
          {items.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-center">
              <p className="text-muted-foreground">Your cart is empty</p>
              <Button
                variant="outline"
                className="mt-4"
                onClick={() => {
                  onOpenChange(false);
                  navigate('/products');
                }}
              >
                Continue Shopping
              </Button>
            </div>
          ) : (
            <div className="space-y-4">
              {items.map((item) => (
                <div
                  key={item.id}
                  className="flex gap-4 p-4 rounded-lg border bg-card"
                >
                  <img
                    src={item.image}
                    alt={item.title}
                    className="h-20 w-20 object-contain rounded"
                  />
                  <div className="flex-1">
                    <h4 className="font-medium line-clamp-2 mb-2">
                      {item.title}
                    </h4>
                    <p className="font-semibold text-primary">
                      ${item.price.toFixed(2)}
                    </p>
                    <div className="flex items-center gap-2 mt-2">
                      <Button
                        variant="outline"
                        size="icon"
                        className="h-8 w-8"
                        onClick={() =>
                          onUpdateQuantity(item.id, Math.max(1, item.quantity - 1))
                        }
                      >
                        <Minus className="h-4 w-4" />
                      </Button>
                      <span className="w-8 text-center font-medium">
                        {item.quantity}
                      </span>
                      <Button
                        variant="outline"
                        size="icon"
                        className="h-8 w-8"
                        onClick={() => onUpdateQuantity(item.id, item.quantity + 1)}
                      >
                        <Plus className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8 ml-auto text-destructive"
                        onClick={() => onRemoveItem(item.id)}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {items.length > 0 && (
          <SheetFooter className="border-t pt-4">
            <div className="w-full space-y-4">
              <div className="flex justify-between text-lg font-semibold">
                <span>Total:</span>
                <span className="text-primary">${total.toFixed(2)}</span>
              </div>
              <Button className="w-full" size="lg" onClick={handleCheckout}>
                Proceed to Checkout
              </Button>
            </div>
          </SheetFooter>
        )}
      </SheetContent>
    </Sheet>
  );
};
